### ISSUE TITLE
ÅÄÖ is correct in Bokus title but not snippet

### ISSUE THREAD

**Issue by IvanHall** [alexandria-org/alexandria#15]
The decoding of special characters åäö seems to be working differently for title and snippet.
The problem seems to affect all bokus.com pages when seraching for https://alexandria.org/?q=site%3Abokus.com

![image](https://user-images.githubusercontent.com/64351454/134798805-4f9c6d85-4350-47d4-a801-d6808b7cfce3.png)

**Comment by joscul** [comment]
This has been fixed.
